### ISSUE TITLE
About the issue of class imbalance

### ISSUE THREAD

**Issue by JJ999888** [jmlipman/RegionWiseLoss#2]
Hello, I would like to know why the region-wise loss mentioned in the article can solve the problem of class imbalance, and how do you prove that it solves the problem of class imbalance? Looking forward to your answer, as it is very important to me.

**Comment by jmlipman** [comment]
Hi,

You can tackle class imbalance with RegionWise loss by giving less importance to the pixels that belong to a certain class (e.g., the background), and/or by giving more importance to pixels that belong to another class (e.g., foreground classes). Here, "importance" means "penalizing more/less heavily misclassifications", i.e., yielding larger/smaller gradients during training. You can see an example of how this can be done in the paper, below Eq. 4, in the sentence that starts with "For instance" and in the following sentence.
